exclude: LICENSE-|.*\.min.js
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
  - repo: https://github.com/crate-ci/typos
    rev: v1.42.1
    hooks:
      - id: typos
  - repo: local
    hooks:
      - id: build
        name: Cargo Build
        entry: cargo build
        language: system
        pass_filenames: false
        files: "^Cargo.toml|\\.rs$"
      - id: fmt
        name: Cargo Format
        entry: cargo fmt --all -- --color always
        language: system
        pass_filenames: false
        files: "^Cargo.toml|\\.rs$"
      - id: check
        name: Cargo Check
        entry: cargo check
        language: system
        pass_filenames: false
        files: "^Cargo.toml|\\.rs$"
      - id: clippy
        name: Cargo Clippy
        entry: cargo clippy -- -D warnings
        language: system
        pass_filenames: false
        files: "^Cargo.toml|\\.rs$"
      - id: test
        name: Cargo Test
        entry: cargo test
        language: system
        pass_filenames: false
        files: "^Cargo.toml|\\.rs$"
